### ISSUE TITLE
[Feature Request] Allow color configuration for placeholder text

### ISSUE THREAD

**Issue by 3raxton** [ssleptsov/ninja-keys#10]
Hey there, 

Great work on this, I love it! I'm working on customizing Ninja Keys on my site and am having issues customizing the color of the placeholder text even with custom CSS.

Is it possible to have this added as a CSS variable anytime in the future or does a way to customize the placeholder already exist? 

Great work again!

**Comment by ssleptsov** [comment]
Hey @3raxton 
Thank you so much! 

Yes, I have added simple placeholder text color variable, you can use it like this:
```css
ninja-keys {
   --ninja-placeholder-color: red;
}
``` 

or if you will need much more styling you can now use `parts` to change input/placeholder or wrapper around it.
```css
ninja-keys::part(ninja-input) {
  color: #14b8a6;
}
ninja-keys::part(ninja-input)::placeholder {
  color: #f43f5e;
}
ninja-keys::part(ninja-input-wrapper) {
  background: rgba(244, 63, 93, 0.3);
}
```
If you will some more styling let me know, here are all available `parts` right now
https://github.com/ssleptsov/ninja-keys#css-shadow-parts

Cheers
