### ISSUE TITLE
--ninja-font-family

### ISSUE THREAD

**Issue by rubjo** [ssleptsov/ninja-keys#22]
🇺🇦

Huge thanks for making this very nice library! Is there any way to set the font-family for the whole modal?

I've tried
```SCSS
.ninja-keys {
    --ninja-font-family: 'Titillium';
    &::part(ninja-input) {
      font-family: var(--ninja-font-family);
    }
}
```

...but have found no way of setting the font for the breadcrumbs.

**Comment by ssleptsov** [comment]
Hmm..weird that font-family was not passed, because it must inherit from parent, like html/body.
Anyway, good catch @rubjo! Thank! I have pushed fix, version 1.2.1 

So, both ways working now in Chrome/FF/Safari for whole modal
```css
ninja-keys {
  font-family: 'Victor Mono', monospace;
}
```
Or with css variable 
```css
ninja-keys {
  --ninja-font-family: 'Victor Mono', monospace;
}
```
Look good with Victor Font too 😀

![Font](https://i.ibb.co/8X6Vt3c/Screenshot-2022-04-22-at-13-13-32.png)
