### ISSUE TITLE
How to custom action-list scroll bar style

### ISSUE THREAD

**Issue by CNFeffery** [ssleptsov/ninja-keys#40]
I use the css below:

```css
/* chrome, edge, not work🙃 */
ninja-keys::part(actions-list)::-webkit-scrollbar-thumb {
  background-color: #bfbfbf;
  outline: none;
  border-radius: 6px;
}

ninja-keys::part(actions-list)::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

/* firefox, work🙂 */
ninja-keys::part(actions-list) {
  scrollbar-width: thin;
}
```
